### ISSUE TITLE
Unsupported operation hgetall/sinter

### ISSUE THREAD

**Issue by tomcooperca** [fppt/jedis-mock#1]
Hi,
Attempting to use this in a Spring JPA integration test. Seems like most commands are not supported by this mock server.

```java.lang.UnsupportedOperationException: Unsupported operation 'hgetall'
	at com.github.fppt.jedismock.commands.RedisOperationExecutor.buildSimpleOperation(RedisOperationExecutor.java:135) ~[jedis-mock-0.1.6.jar:na]
	at com.github.fppt.jedismock.commands.RedisOperationExecutor.execCommand(RedisOperationExecutor.java:154) ~[jedis-mock-0.1.6.jar:na]
...
java.lang.UnsupportedOperationException: Unsupported operation 'sinter'
	at com.github.fppt.jedismock.commands.RedisOperationExecutor.buildSimpleOperation(RedisOperationExecutor.java:135) ~[jedis-mock-0.1.6.jar:na]
	at com.github.fppt.jedismock.commands.RedisOperationExecutor.execCommand(RedisOperationExecutor.java:154) ~[jedis-mock-0.1.6.jar:na]
```

**Comment by fppt** [comment]
Hi,

The mock is not comprehensive yet. If you can provide a list of commands you would like added to the mock I can see about implementing those.

**Comment by fppt** [comment]
Will look at adding `sinter` and `hgetall `

**Comment by fppt** [comment]
Currently implemented here: https://github.com/fppt/jedis-mock/pull/7

**Comment by fppt** [comment]
Hey, thanks for the list. I doubt I will get around to implementing all of them right away. I tend to go one a need by need basis. So if one of them is blocking or hindering your use of `jedis-mock` then give me a shout and I will get around to adding them.

For the moment hgetall/sinter are now part of the 0.1.8 release: https://github.com/fppt/jedis-mock/releases/tag/v0.1.8 . Thanks for the feature request.
