### ISSUE TITLE
RO_zremrangebyscore#getStartScore does not work for negative scores

### ISSUE THREAD

**Issue by xcronic** [fppt/jedis-mock#116]
"-1".charAt(0) = '-' 
AND 
java.lang.Character#isDigit('-') = false
==>
ERROR com.github.fppt.jedismock.operations.RO_exec - ERROR during committing transaction
com.github.fppt.jedismock.exception.WrongValueTypeException: Valid start must be a number or start with '(' or be equal to '-inf'
	at com.github.fppt.jedismock.operations.RO_zremrangebyscore.getStartScore(RO_zremrangebyscore.java:79) ~[jedis-mock-0.1.18.jar:?]
	at com.github.fppt.jedismock.operations.RO_zremrangebyscore.response(RO_zremrangebyscore.java:36) ~[jedis-mock-0.1.18.jar:?]
	at com.github.fppt.jedismock.operations.AbstractRedisOperation.execute(AbstractRedisOperation.java:47) ~[jedis-mock-0.1.18.jar:?]
	at com.github.fppt.jedismock.operations.RO_zremrangebyscore.execute(RO_zremrangebyscore.java:18) ~[jedis-mock-0.1.18.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at com.github.fppt.jedismock.operations.RO_exec.execute(RO_exec.java:25) [jedis-mock-0.1.18.jar:?]
	at com.github.fppt.jedismock.server.RedisOperationExecutor.execCommand(RedisOperationExecutor.java:36) [jedis-mock-0.1.18.jar:?]
	at com.github.fppt.jedismock.server.RedisClient.run(RedisClient.java:54) [jedis-mock-0.1.18.jar:?]

**Comment by xcronic** [comment]
RO_zremrangebyscore.java:79

**Comment by inponomarev** [comment]
Already noticed this! This will be fixed soon in the next release together with `ZRANGEBYSCORE` implementation.

**Comment by inponomarev** [comment]
the fix is to be included in 0.1.19
