### ISSUE TITLE
Operation 'hsetnx' not implemented

### ISSUE THREAD

**Issue by rfelgent** [fppt/jedis-mock#13]
Hello,

I get following error
`
Caused by: redis.clients.jedis.exceptions.JedisDataException: Unsupported operation 'hsetnx'
	at redis.clients.jedis.Protocol.processError(Protocol.java:127)
	at redis.clients.jedis.Protocol.process(Protocol.java:161)
	at redis.clients.jedis.Protocol.read(Protocol.java:215)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
	at redis.clients.jedis.Connection.getIntegerReply(Connection.java:265)
	at redis.clients.jedis.BinaryJedis.hsetnx(BinaryJedis.java:870)
`

Greetings

**Comment by fppt** [comment]
`hsetnx` is not yet supported, I will be sure to add it for the next release. Thanks for raising the issue!

**Comment by fppt** [comment]
This is being addressed here: https://github.com/fppt/jedis-mock/pull/18

**Comment by fppt** [comment]
This is now supported: https://github.com/fppt/jedis-mock/releases/tag/v0.1.9
