### ISSUE TITLE
rpoplpush fails with ParseErrorException

### ISSUE THREAD

**Issue by imanzano** [fppt/jedis-mock#54]
Versions
jedis               = 'redis.clients:jedis:3.0.1'
jedisMock           = 'com.github.fppt:jedis-mock:0.1.14'

I do

`jedis.rpoplpush(queueName, "processing")`

I got

Exception in thread "Thread-4" com.github.fppt.jedismock.exception.ParseErrorException
	at com.github.fppt.jedismock.server.SliceParser.consumeLong(SliceParser.java:51)
	at com.github.fppt.jedismock.server.SliceParser.consumeParameter(SliceParser.java:114)
	at com.github.fppt.jedismock.server.SliceParser.consumeParameter(SliceParser.java:127)
	at com.github.fppt.jedismock.operations.RO_rpoplpush.response(RO_rpoplpush.java:22)
	at com.github.fppt.jedismock.operations.AbstractRedisOperation.execute(AbstractRedisOperation.java:47)
	at com.github.fppt.jedismock.server.RedisOperationExecutor.execCommand(RedisOperationExecutor.java:43)
	at com.github.fppt.jedismock.server.RedisClient.run(RedisClient.java:54)
	at java.lang.Thread.run(Thread.java:748)

java.net.SocketTimeoutException: Read timed out
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
	at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:205)
	at redis.clients.jedis.util.RedisInputStream.readByte(RedisInputStream.java:43)
	at redis.clients.jedis.Protocol.process(Protocol.java:154)
	at redis.clients.jedis.Protocol.read(Protocol.java:219)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:309)
	at redis.clients.jedis.Connection.getBinaryBulkReply(Connection.java:255)
	at redis.clients.jedis.Connection.getBulkReply(Connection.java:245)
	at redis.clients.jedis.Jedis.rpoplpush(Jedis.java:1195)

**Comment by imanzano** [comment]
Maybe It can help

<img width="831" alt="Screen Shot 2019-07-26 at 1 23 12 PM" src="https://user-images.githubusercontent.com/146508/61966330-c2dada80-afa8-11e9-8caf-6b68e1ff3578.png">

**Comment by imanzano** [comment]
I did a fix. It is available in PR 55

**Comment by fppt** [comment]
PR merged and released in: https://github.com/fppt/jedis-mock/releases/tag/v0.1.15

Thanks for the contribution!
