### ISSUE TITLE
Unsupported operation 'hlen' 

### ISSUE THREAD

**Issue by jchmb** [fppt/jedis-mock#61]
**Version: 0.1.15**

Sep 27, 2019 6:23:01 PM com.github.fppt.jedismock.server.RedisOperationExecutor execCommand
SEVERE: Malformed request
java.lang.UnsupportedOperationException: Unsupported operation 'hlen'
	at com.github.fppt.jedismock.operations.OperationFactory.buildTxOperation(OperationFactory.java:89)
	at com.github.fppt.jedismock.server.RedisOperationExecutor.execCommand(RedisOperationExecutor.java:39)
	at com.github.fppt.jedismock.server.RedisClient.run(RedisClient.java:54)
	at java.lang.Thread.run(Thread.java:748)

**Comment by fppt** [comment]
Released in: https://github.com/fppt/jedis-mock/releases/tag/v0.1.16

Thanks @davidkus !
